######################################
# NOTE: Before running this pipeline to generate a new nuget package, update the version string in two places
#      1) update the name: string below (line 6)     -- this is the version for the nuget package (e.g. 1.0.0)
#      2) update \libs\host\GarnetServer.cs readonly string version  (~line 45)   -- NOTE - these two values need to be the same 
###################################### 
name: 1.0.15
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - .azure/pipelines/azure-pipelines-external-release.yml
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main

jobs:
- job: Phase_1
  displayName: Assessment
  cancelTimeoutInMinutes: 1
  pool:
    name: Azure Pipelines
  steps:
  - checkout: self
    clean: False
    submodules: recursive
    persistCredentials: True
  - task: UseDotNet@2
    displayName: Use .NET Core sdk 6.0.x
    inputs:
      version: 6.0.x
  - task: UseDotNet@2
    displayName: Use .NET Core sdk 7.0.x
    inputs:
      version: 7.0.x
  - task: UseDotNet@2
    displayName: Use .NET Core sdk 8.0.x
    inputs:
      version: 8.0.x
  - task: NuGetToolInstaller@1
    displayName: Nuget Tool Installer
    inputs:
      versionspec: '*'
      checkLatest: true
  - task: NuGetAuthenticate@1
    displayName: NuGet Authenticate
  - task: NuGetAuthenticate@1
    displayName: 'NuGet Authenticate'

  - task: Docker@2
    displayName: BROKEN BROKEN Build and push an image to container registry
    enabled: False
    inputs:
      command: buildAndPush
      repository: 'garnetacr.azurecr.io/garnet'
      dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
      containerRegistry: 'GarnetDockerACRConnection'
      tags: '$(Build.BuildId)'

  - task: AzureCLI@2
    displayName: DEBUG DEBUG Build and List out containers in Azure NON PRODUCTION Sub ACR
    enabled: True
    inputs:
      azureSubscription: 'GarnetNONPRODACRConnection' 
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az acr login --name garnetacrcontainer
        az acr build --registry garnetacrcontainer --image garnetbase2:$(Build.BuildId) --file Dockerfile $(Build.SourcesDirectory)
        az acr repository list --name garnetacrcontainer.azurecr.io/garnet --output table

  - task: Docker@2
    displayName: Login to ACR using Docker service connection
    enabled: False
    inputs:
      command: login
      containerRegistry: GarnetNONPRODDockerACRConnection

  - task: Docker@2
    displayName: DEBUG Build ONLY an image to NON PROD ACR
    enabled: True
    inputs:
      command: build
      repository: 'garnetbase3'
      dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
      tags: '$(Build.BuildId)'

  - task: Docker@1
    displayName: 'DEBUG Using Docker 1 - Push an image'
    enabled: True
    inputs:
      azureSubscriptionEndpoint: GarnetNONPRODACRConnection
      azureContainerRegistry: garnetacrcontainer
      command: 'Push an image'
      imageName: 'garnetbase3'


  - task: Docker@2
    displayName: DEBUG Push ONLY an image to NON PROD ACR
    enabled: True
    inputs:
      command: push
      repository: 'garnetbase3'
      containerRegistry: 'GarnetNONPRODDockerACRConnection'

  - task: AzureCLI@2
    displayName: DEBUG DEBUG List out containers in Azure NON PRODUCTION Sub ACR
    enabled: True
    inputs:
      azureSubscription: 'GarnetNONPRODACRConnection' 
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az acr login --name garnetacrcontainer
        az acr repository list --name garnetacrcontainer.azurecr.io/garnet --output table


  - task: Docker@2
    displayName: DEBUG Build and push an image to NON PROD ACR
    enabled: True
    inputs:
      command: buildAndPush
      repository: 'garnetimage01'
      dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
      containerRegistry: 'GarnetNONPRODDockerACRConnection'
      tags: '$(Build.BuildId)'

  - task: AzureCLI@2
    displayName: DEBUG DEBUG List out containers in Azure Prod Sub ACR
    enabled: False
    inputs:
      azureSubscription: 'GarnetACRConnection' 
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az acr login --name garnetacr
        az acr repository list --name garnetacr.azurecr.io/garnet --output table

  - task: DotNetCoreCLI@2
    displayName: dotnet build
    enabled: False
    inputs:
      projects: '**/Garnet.*.csproj'
      arguments: -c Release

  - task: PowerShell@2
    displayName: 'Publish the GarnetServer binaries'
    enabled: False
    inputs:
      filePath: .azure/pipelines/createbinaries.ps1 
      arguments: 1
      workingDirectory: .azure/pipelines

  - task: EsrpCodeSigning@5
    displayName: Sign the binaries for nuget and zipped files
    enabled: False
    inputs:
      ConnectedServiceName: 'GarnetCodeSigningOneCert'
      AppRegistrationClientId: '19bbb452-ce7a-4b3d-bdc4-42a0090e797b'
      AppRegistrationTenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47'
      AuthAKVName: 'GarnetCodeSignKV'
      AuthCertName: 'Garnet-CodeSign-AuthCert'
      AuthSignCertName: 'Garnet-CodeSigning-SigningCertificate'
      FolderPath: .
      Pattern: Garnet.server.dll,Garnet.client.dll,Garnet.common.dll,Garnet.cluster.dll,Garnet.host.dll,HdrHistogram.dll,Tsavorite.core.dll,Tsavorite.devices.AzureStorageDevice.dll,native_device.dll,GarnetServer.exe
      signConfigType: inlineSignParams
      inlineOperation: >-
        [
            {
                  "KeyCode" : "CP-230012",
                  "OperationCode" : "SigntoolSign",
                  "Parameters" : {
                      "OpusName" : "Microsoft",
                      "OpusInfo" : "http://www.microsoft.com",
                      "FileDigest" : "/fd \"SHA256\"",
                      "PageHash" : "/NPH",
                      "TimeStamp" : "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                  },
                  "ToolName" : "sign",
                  "ToolVersion" : "1.0"
            },
            {
                  "KeyCode" : "CP-230012",
                  "OperationCode" : "SigntoolVerify",
                  "Parameters" : {},
                  "ToolName" : "sign",
                  "ToolVersion" : "1.0"
            }
         ]
      SessionTimeout: 20
      VerboseLogin: true      

  - task: NuGetCommand@2
    displayName: nuget pack Garnet
    enabled: False
    inputs:
      command: custom
      arguments: pack Garnet.nuspec -OutputDirectory $(Build.ArtifactStagingDirectory) -Symbols -SymbolPackageFormat snupkg -version $(Build.BuildNumber) -Verbosity Detailed

  # Do after Nuget Pack so not part of Nuget Pack
  - task: PowerShell@2
    displayName: 'Zip the GarnetServer binaries'
    enabled: False
    inputs:
      filePath: .azure/pipelines/createbinaries.ps1 
      arguments: 2
      workingDirectory: .azure/pipelines

  - task: CopyFiles@2
    displayName: 'Copy Zipped Files to Artifacts dir: $(Build.artifactstagingdirectory)'
    enabled: False
    inputs:
      Contents: '**'
      SourceFolder: '$(Build.SourcesDirectory)/main/GarnetServer/bin/Release/net8.0/publish/output'
      TargetFolder: $(build.artifactstagingdirectory)

  - task: EsrpCodeSigning@5
    displayName: Sign the NuGet Package 
    enabled: False
    inputs:
      ConnectedServiceName: 'GarnetCodeSigningOneCert'
      AppRegistrationClientId: '19bbb452-ce7a-4b3d-bdc4-42a0090e797b'
      AppRegistrationTenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47'
      AuthAKVName: 'GarnetCodeSignKV'
      AuthCertName: 'Garnet-CodeSign-AuthCert'
      AuthSignCertName: 'Garnet-CodeSigning-SigningCertificate'
      FolderPath: $(Build.ArtifactStagingDirectory)
      Pattern: Microsoft.Garnet.*.nupkg
      signConfigType: inlineSignParams
      inlineOperation: >-
        [
            {
                  "KeyCode" : "CP-401405",
                  "OperationCode" : "NuGetSign",
                  "Parameters" : {
                      "OpusName" : "Microsoft",
                      "OpusInfo" : "http://www.microsoft.com",
                      "FileDigest" : "/fd \"SHA256\"",
                      "PageHash" : "/NPH",
                      "TimeStamp" : "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                  },
                  "ToolName" : "sign",
                  "ToolVersion" : "1.0"
            },
            {
                  "KeyCode" : "CP-401405",
                  "OperationCode" : "NuGetVerify",
                  "Parameters" : {},
                  "ToolName" : "sign",
                  "ToolVersion" : "1.0"
            }
         ]
      SessionTimeout: 20
      VerboseLogin: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    enabled: False

  - task: GitHubRelease@0
    displayName: 'Create the GitHub release'
    enabled: False
    inputs:
      action: 'create'
      gitHubConnection: ADO_to_Github_ServiceConnection
      tagSource: manual
      tag: 'v$(Build.BuildNumber)'
      title: 'Garnet v$(Build.BuildNumber)'
      releaseNotesSource: input
      releaseNotes: |
       Get NuGet binaries at:
       * https://www.nuget.org/packages/Microsoft.Garnet

       More information at:
       * https://microsoft.github.io/garnet
       * https://github.com/microsoft/garnet
       * https://www.microsoft.com/en-us/research/project/garnet
     
      assets: |
        $(Build.ArtifactStagingDirectory)/*.nupkg
        $(Build.ArtifactStagingDirectory)/*.zip
        $(Build.ArtifactStagingDirectory)/*.tar.xz
        $(Build.ArtifactStagingDirectory)/*.7z

  - task: NuGetCommand@2
    displayName: 'Push to NuGet.org'
    enabled: False
    inputs:
      command: push
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
      nuGetFeedType: external
      publishFeedCredentials: GarnetADO_to_Nuget