trigger:
  branches:
    include:
      - refs/heads/main

resources:
  repositories:
  - repository: self
    type: git

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs: 
- job: 'Linux'
  pool:
    name: GarnetPerfCI_Linux_Pool
    vmImage: GarnetPerfCI_LinuxImage
  displayName: 'Linux'
  timeoutInMinutes: 75

  steps:
  - task: UseDotNet@2
    displayName: Use .NET 8.0
    inputs:
      packageType: 'sdk'
      version: '8.0.x'

  - bash: |
      sudo npm install -g azurite
      sudo mkdir azurite
      sudo azurite --silent --location azurite --debug azurite\debug.log &
    displayName: 'Install and Run Azurite'
      
  - task: NuGetAuthenticate@1
    displayName: Nuget Authenticate

  - task: UseDotNet@2 # Optional if the .NET Core SDK is already installed
    displayName: Use .NET

  - script: dotnet restore
    displayName: .NET Restore

  - task: PowerShell@2
    displayName: '1: BDN.benchmark '
    continueOnError: true
    enabled: true
    inputs:
      targetType: filePath
      filePath: './test/BDNPerfTests/run_bdnperftest.ps1'
      arguments: 'CI_BDN_Config_RespParseStress.json'
      workingDirectory: test/BDNPerfTests

  - task: CopyFiles@2
    displayName: 'Copy Results Files to: $(build.artifactstagingdirectory)'
    inputs:
      Contents: '**/test/BDNPerfTests/results/**/*'
      TargetFolder: $(build.artifactstagingdirectory)

  - task: CopyFiles@2
    displayName: 'Copy ErrorLog Files to: $(build.artifactstagingdirectory)'
    inputs:
      Contents: '**/test/BDNPerfTests/errorlog/**/*'
      TargetFolder: $(build.artifactstagingdirectory)

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact Output Files: LogResultFiles'
    inputs:
      ArtifactName: LogAndResultFiles

- job: Windows 
  displayName: Windows
  cancelTimeoutInMinutes: 1

  pool:
    name: GarnetPerfCI_Pool
    vmImage: GarnetPerfCI_WindowsImage
  steps:
  - checkout: self
    clean: False
    submodules: recursive
    persistCredentials: True
   
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk 8.0.x'
    inputs:
      version: 8.0.x
   
  - task: NuGetToolInstaller@1
    displayName: Nuget Tool Installer
    inputs:
      versionspec: '*'
      checkLatest: true

  - task: NuGetAuthenticate@1
    displayName: 'NuGet Authenticate'

  - task: PowerShell@2
    displayName: '1: Resp.Benchmark ONLINE; Get Set; 1 Thread'
    continueOnError: true
    enabled: true
    inputs:
      targetType: filePath
      filePath: './test/BDNPerfTests/run_bdnperftest.ps1'
      arguments: 'CI_BDN_Config_RespParseStress.json'
      workingDirectory: test/BDNPerfTests

  - task: CopyFiles@2
    displayName: 'Copy Results Files to: $(build.artifactstagingdirectory)'
    inputs:
      Contents: '**/test/BDNPerfTests/results/**/*'
      TargetFolder: $(build.artifactstagingdirectory)

  - task: CopyFiles@2
    displayName: 'Copy ErrorLog Files to: $(build.artifactstagingdirectory)'
    inputs:
      Contents: '**/test/BDNPerfTests/errorlog/**/*'
      TargetFolder: $(build.artifactstagingdirectory)

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact Output Files: LogResultFiles'
    inputs:
      ArtifactName: LogAndResultFiles
